export const GET_TOVARS_FOR_BOOKMARKS = 'GET_TOVARS_FOR_BOOKMARKS';
export const GET_TOVARS_FOR_BOOKMARKS_FULFILLED = 'GET_TOVARS_FOR_BOOKMARKS_FULFILLED';

export const CHANGE_SOMEBODY = 'CHANGE_SOMEBODY';
export const GET_CITIES_BY_REGION = 'GET_CITIES_BY_REGION';
export const GET_CITIES_BY_REGION_FULFILLED = 'GET_CITIES_BY_REGION_FULFILLED';
export const GET_SKLAD = 'GET_SKLAD';
export const GET_SKLAD_FULFILLED = 'GET_SKLAD_FULFILLED';

export const GET_COMMENT_COUNTER_BY_URLS = 'GET_COMMENT_COUNTER_BY_URLS';
export const GET_COMMENT_COUNTER_BY_URLS_FULFILLED = 'GET_COMMENT_COUNTER_BY_URLS_FULFILLED';

export const GET_VIEWS_COUNTER_BY_URLS = 'GET_VIEWS_COUNTER_BY_URLS';
export const GET_VIEWS_COUNTER_BY_URLS_FULFILLED = 'GET_VIEWS_COUNTER_BY_URLS_FULFILLED';

export const SCREEN_TYPE_CHANGED = 'SCREEN_TYPE_CHANGED';

export const LOG_OUT = 'LOG_OUT';
export const LOG_OUT_FULFILLED = 'LOG_OUT_FULFILLED';

export const GET_POST = 'GET_POST';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';

export const GET_AUTO_MARKS_REQUEST = 'GET_AUTO_MARKS_REQUEST';
export const GET_AUTO_MARKS_SUCCESS = 'GET_AUTO_MARKS_SUCCESS';

export const GET_AUTO_MODELS_REQUEST = 'GET_AUTO_MODELS_REQUEST';
export const GET_AUTO_MODELS_SUCCESS = 'GET_AUTO_MODELS_SUCCESS';

export const GET_AUTO_YEARS_REQUEST = 'GET_AUTO_YEARS_REQUEST';
export const GET_AUTO_YEARS_SUCCESS = 'GET_AUTO_YEARS_SUCCESS';

export const GET_AUTO_MODIFICATIONS_REQUEST = 'GET_AUTO_MODIFICATIONS_REQUEST';
export const GET_AUTO_MODIFICATIONS_SUCCESS = 'GET_AUTO_MODIFICATIONS_SUCCESS';

export const GET_AUTO_BODYS_REQUEST = 'GET_AUTO_BODYS_REQUEST';
export const GET_AUTO_BODYS_SUCCESS = 'GET_AUTO_BODYS_SUCCESS';

export const GET_AUTO_BY_NAMES = 'GET_AUTO_BY_NAMES';

export const GET_PROMO_BLOCKS = 'GET_PROMO_BLOCKS';
export const GET_PROMO_BLOCKS_REQUEST = 'GET_PROMO_BLOCKS_REQUEST';
export const GET_PROMO_BLOCKS_SUCCESS = 'GET_PROMO_BLOCKS_SUCCESS';

export const GET_GOODS_CATEGORIES_REQUEST = 'GET_GOODS_CATEGORIES_REQUEST';
export const GET_GOODS_CATEGORIES_SUCCESS = 'GET_GOODS_CATEGORIES_SUCCESS';

export const GET_POPULAR_BRANDS_REQUEST = 'GET_POPULAR_BRANDS_REQUEST';
export const GET_POPULAR_BRANDS_SUCCESS = 'GET_POPULAR_BRANDS_SUCCESS';

export const GET_PRODUCT_CATEGORY_OPTIONS_REQUEST = 'GET_PRODUCT_CATEGORY_OPTIONS_REQUEST';
export const GET_PRODUCT_CATEGORY_OPTIONS_SUCCESS = 'GET_PRODUCT_CATEGORY_OPTIONS_SUCCESS';

export const SET_CURRENT_USER_CAR = 'SET_CURRENT_USER_CAR';
export const SET_USER_CURRENT_CAR_INDEX_PENDING = 'SET_USER_CURRENT_CAR_INDEX_PENDING';
export const SET_USER_CURRENT_CAR_INDEX_FULFILLED = 'SET_USER_CURRENT_CAR_INDEX_FULFILLED';


export const ADD_USER_CAR = 'ADD_USER_CAR';
export const ADD_USER_CAR_FULFILLED = 'ADD_USER_CAR_FULFILLED';
export const DELETE_USER_CAR = 'DELETE_USER_CAR';
export const DELETE_USER_CAR_FULFILLED = 'DELETE_USER_CAR_FULFILLED';
export const SET_USER_CURRENT_CAR_INDEX = 'SET_USER_CURRENT_CAR_INDEX';
export const RESET_USER_CURRENT_CAR_INDEX = 'RESET_USER_CURRENT_CAR_INDEX';
export const GET_USER_CURRENT_CAR_INDEX = 'GET_USER_CURRENT_CAR_INDEX';
export const GET_USER_CURRENT_CAR_INDEX_FULFILLED = 'GET_USER_CURRENT_CAR_INDEX_FULFILLED';
export const GET_USER_CARS = 'GET_USER_CARS';
export const GET_USER_CARS_FULFILLED = 'GET_USER_CARS_FULFILLED';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_FULFILLED = 'GET_USER_INFO_FULFILLED';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const GET_USER_DELIVERY_ADDRESS = 'GET_USER_DELIVERY_ADDRESS';
export const GET_USER_DELIVERY_ADDRESS_FULFILLED = 'GET_USER_DELIVERY_ADDRESS_FULFILLED';


export const GET_USER_BAG = 'GET_USER_BAG';
export const GET_USER_BAG_FULFILLED = 'GET_USER_BAG_FULFILLED';
export const ADD_USER_BAG = 'ADD_USER_BAG';
export const ADD_USER_BAG_FULFILLED = 'ADD_USER_BAG_FULFILLED';
export const DELETE_USER_BAG = 'DELETE_USER_BAG';
export const DELETE_USER_BAG_FULFILLED = 'DELETE_USER_BAG_FULFILLED';
export const GET_USER_FAVORITES = 'GET_USER_FAVORITES';
export const GET_USER_FAVORITES_FULFILLED = 'GET_USER_FAVORITES_FULFILLED';
export const ADD_USER_FAVORITES = 'ADD_USER_FAVORITES';
export const ADD_USER_FAVORITES_FULFILLED = 'ADD_USER_FAVORITES_FULFILLED';
export const DELETE_USER_FAVORITES = 'DELETE_USER_FAVORITES';
export const DELETE_USER_FAVORITES_FULFILLED = 'DELETE_USER_FAVORITES_FULFILLED';





export const GET_LAST_CREATED_POSTS = 'GET_LAST_CREATED_POSTS';
export const GET_LAST_CREATED_POSTS_FULFILLED = 'GET_LAST_CREATED_POSTS_FULFILLED';

export const GET_HIT_SALES_CATEGORIES = 'GET_HIT_SALES_CATEGORIES';
export const GET_HIT_SALES_BY_CATEGORIES = 'GET_HIT_SALES_BY_CATEGORIES';
export const GET_HIT_SALES_CATEGORIES_FULFILLED = 'GET_HIT_SALES_CATEGORIES_FULFILLED';
export const GET_HIT_SALES_BY_CATEGORIES_FULFILLED = 'GET_HIT_SALES_BY_CATEGORIES_FULFILLED';

export const GET_POPULAR_AUTO = 'GET_POPULAR_AUTO';
export const GET_POPULAR_AUTO_FULFILLED = 'GET_POPULAR_AUTO_FULFILLED';

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_PENDING = 'GET_SEARCH_RESULT_PENDING';
export const GET_SEARCH_RESULT_FULFILLED = 'GET_SEARCH_RESULT_FULFILLED';


export const SET_SEARCH_OPTION = 'SET_SEARCH_OPTION';
export const SET_SEARCH_STR = 'SET_SEARCH_STR';
export const SET_SEARCH_SHARE = 'SET_SEARCH_SHARE';
export const SET_SEARCH_NEW = 'SET_SEARCH_NEW';
export const SET_SEARCH_DISCOUNT = 'SET_SEARCH_DISCOUNT';
export const SET_SEARCH_TOP_SALLER = 'SET_SEARCH_TOP_SALLER';
export const RESET_SPECIFIC_OPTION = 'RESET_SPECIFIC_OPTION';
export const RESET_OPTION = 'RESET_OPTION';


export const SET_SEARCH_OPTION_ONLY_VALUE = 'SET_SEARCH_OPTION_ONLY_VALUE';
export const SET_SEARCH_PRODUCT_SPECIFIC_OPTION = 'SET_SEARCH_PRODUCT_SPECIFIC_OPTION';

export const SET_SEARCH_PAGE = 'SET_SEARCH_PAGE';
export const SET_SEARCH_LIMIT = 'SET_SEARCH_LIMIT';
export const SET_SEARCH_SORT = 'SET_SEARCH_SORT';
export const SET_SEARCH_PRICE_FROM = 'SET_SEARCH_PRICE_FROM';
export const SET_SEARCH_PRICE_TO = 'SET_SEARCH_PRICE_TO';

export const GET_SEARCH_RESULT_COUNTERS = 'GET_SEARCH_RESULT_COUNTERS';
export const SET_SEARCH_RESULT_COUNTERS = 'SET_SEARCH_RESULT_COUNTERS';

export const GET_SEARCH_RESULT_REGULAR_COUNTERS = 'GET_SEARCH_RESULT_REGULAR_COUNTERS';
export const SET_SEARCH_RESULT_REGULAR_COUNTERS = 'SET_SEARCH_RESULT_REGULAR_COUNTERS';

export const GET_SEARCH_RESULT_SPECIFIC_COUNTERS = 'GET_SEARCH_RESULT_SPECIFIC_COUNTERS';
export const SET_SEARCH_RESULT_SPECIFIC_COUNTERS = 'SET_SEARCH_RESULT_SPECIFIC_COUNTERS';

export const GET_PRODUCT_RUBRIC_REQUEST = 'GET_PRODUCT_RUBRIC_REQUEST';
export const GET_PRODUCT_RUBRIC_SUCCESS = 'GET_PRODUCT_RUBRIC_SUCCESS';

export const GET_PRODUCT_RUBRIC_ID_BY_REWRITE_REQUEST = 'GET_PRODUCT_RUBRIC_ID_BY_REWRITE_REQUEST';
export const GET_PRODUCT_RUBRIC_ID_BY_REWRITE_SUCCESS = 'GET_PRODUCT_RUBRIC_ID_BY_REWRITE_SUCCESS';

export const GET_SEO = 'GET_SEO';
export const GET_SEO_FULFILLED = 'GET_SEO_FULFILLED';

export const GET_MENU_CAR_CATEGORY = 'GET_MENU_CAR_CATEGORY';
export const GET_MENU_CAR_CATEGORY_FULFILLED = 'GET_MENU_CAR_CATEGORY_FULFILLED';

export const GET_COMMENT = 'GET_COMMENT';
export const GET_COMMENT_FULFILLED = 'GET_COMMENT_FULFILLED';
export const VOTE_COMMENT = 'VOTE_COMMENT';

export const GET_COMMENT_STRUCTURE_REQUEST = 'GET_COMMENT_STRUCTURE_REQUEST';
export const GET_COMMENT_STRUCTURE_RESPONSE = 'GET_COMMENT_STRUCTURE_RESPONSE';

export const GET_TOVAR = 'GET_TOVAR';
export const GET_TOVAR_PROPS_ALL= 'GET_TOVAR_PROPS_ALL';
export const GET_TOVAR_PROPS_ALL_FULFILLED = 'GET_TOVAR_PROPS_ALL_FULFILLED';
export const GET_TOVAR_FULFILLED = 'GET_TOVAR_FULFILLED';
export const GET_TOVAR_PHOTOS = 'GET_TOVAR_PHOTOS';
export const GET_TOVAR_PHOTOS_FULFILLED = 'GET_TOVAR_PHOTOS_FULFILLED';
export const GET_TOVAR_DESCRIPTION = 'GET_TOVAR_DESCRIPTION';
export const GET_TOVAR_DESCRIPTION_FULFILLED = 'GET_TOVAR_DESCRIPTION_FULFILLED';
export const GET_TOVAR_SPECIFY_PARAMS = 'GET_TOVAR_SPECIFY_PARAMS';

export const GET_TOVARS_BAG = 'GET_TOVARS_BAG';
export const GET_TOVARS_BAG_FULFILLED = 'GET_TOVARS_BAG_FULFILLED';
export const GET_TOVARS_BAG_COUNTERS = 'GET_TOVARS_BAG_COUNTERS';
export const GET_TOVARS_BAG_COUNTERS_FULFILLED = 'GET_TOVARS_BAG_COUNTERS_FULFILLED';
export const SET_TOVARS_BAG_COUNTERS = 'SET_TOVARS_BAG_COUNTERS';
export const SET_TOVARS_BAG_COUNTERS_FULFILLED = 'SET_TOVARS_BAG_COUNTERS_FULFILLED';

export const GET_SUITABLE = 'GET_SUITABLE';
export const GET_SUITABLE_ALL = 'GET_SUITABLE_ALL';
export const SET_SUITABLE_ALL = 'SET_SUITABLE_ALL';
export const GET_SUITABLE_FULFILLED = 'GET_SUITABLE_FULFILLED';
export const GET_ALTERNATIVE = 'GET_ALTERNATIVE';
export const GET_ALTERNATIVE_FULFILLED = 'GET_ALTERNATIVE_FULFILLED';
export const GET_RECOMMENDED = 'GET_RECOMMENDED';
export const GET_RECOMMENDED_FULFILLED = 'GET_RECOMMENDED_FULFILLED';


export const GET_MODEL_TOVARS = 'GET_MODEL_TOVARS';
export const GET_TOVARS = 'GET_TOVARS';
export const GET_TOVARS_FULFILLED = 'GET_TOVARS_FULFILLED';
export const GET_TOVARS_BY_MODEL = 'GET_TOVARS_BY_MODEL';
export const GET_TOVARS_BY_MODEL_FULFILLED = 'GET_TOVARS_BY_MODEL_FULFILLED';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const SET_PATH_PAGE_PARAMETERS = 'SET_PATH_PAGE_PARAMETERS';
export const TOGGLE_COMMENT_FIELD = 'TOGGLE_COMMENT_FIELD';
export const UPDATE_COMMENT_FIELD = 'UPDATE_COMMENT_FIELD';
export const APPEND_COMMENT_FIELD = 'APPEND_COMMENT_FIELD';
export const SET_COMMENT_ONLY_FIELD = 'SET_COMMENT_ONLY_FIELD';
export const DELETE_COMMENT_FIELD = 'DELETE_COMMENT_FIELD';
export const SAVE_COMMENT = 'SAVE_COMMENT';

export const GET_SITE_COMMENTS = 'GET_SITE_COMMENTS';
export const GET_SITE_COMMENTS_FULFILLED = 'GET_SITE_COMMENTS_FULFILLED';
export const GET_SITE_COMMENTS_ANSWERS_FULFILLED = 'GET_SITE_COMMENTS_ANSWERS_FULFILLED';
export const GET_SITE_COMMENTS_STAT_FULFILLED = 'GET_SITE_COMMENTS_STAT_FULFILLED';


export const SUBSCRIBE_FULFILLED = 'SUBSCRIBE_FULFILLED';


export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_FULFILLED = 'GET_QUESTIONS_FULFILLED';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_ANSWER = 'SAVE_ANSWER';

export const SET_WATCHED_ITEM = 'SET_WATCHED_ITEM';

export const GET_WATCHED_ITEM = 'GET_WATCHED_ITEM';
export const GET_WATCHED_ITEM_FULFILLED = 'GET_WATCHED_ITEM_FULFILLED';

export const CHECK_SHOP = 'CHECK_SHOP';
export const CHECK_SHOP_FULFILLED = 'CHECK_SHOP_FULFILLED';

export const CHECK_SHARE = 'CHECK_SHARE';
export const CHECK_SHARE_FULFILLED = 'CHECK_SHARE_FULFILLED';


export const ALL_POPUP = 'ALL_POPUP';
export const SEARCH_COUNTER_PANEL = 'SEARCH_COUNTER_PANEL';
export const SEARCH_LOADER = 'SEARCH_LOADER';

export const SET_ACTIVE_CERTIFICATE = 'SET_ACTIVE_CERTIFICATE';


